language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-26.0.2
    - android-27
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - '.+'
    
before_script:
  - echo yes | android update sdk --no-ui --all --filter platform-tools,tools
  - echo yes | android update sdk --no-ui --all --filter build-tools-27.0.2
  - echo yes | android update sdk --no-ui --all --filter android-27

script:
- ./gradlew clean tes